import { StyleSheet } from 'react-native';

const getStyles = (theme = 'light') => {
    const themeStyles = {
        light: {
            backgroundColor: 'rgba(1, 193, 219, 1)',
            textColor: 'rgb(57, 63, 67)', 
            inputBackground: 'white',
            borderColor: 'rgba(0, 0, 0, 0.5)',
            containerBackground: 'white', 
            cardBackground: 'white', 
        },
        dark: {
            backgroundColor: 'rgba(1, 193, 219, 1)', 
            textColor: 'rgb(255, 255, 255)', 
            inputBackground: 'rgb(28, 28, 30)', 
            borderColor: 'rgba(255, 255, 255, 0.5)', 
            containerBackground: 'rgb(0, 0, 0)', 
            containerBackground: '#1A1A1A',
            cardBackground: 'rgb(50, 50, 52)',  
        },
    };

    return StyleSheet.create({
        container: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            paddingTop: '5%',
            padding: '5%',
            backgroundColor: themeStyles[theme].containerBackground,
            
        },
        containerCommentScreen: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            paddingTop: '0%',
            padding: '5%',
            backgroundColor: themeStyles[theme].containerBackground, 
        },
        containerWithoutBackground: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
        },
        backgroundImage: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
        },
        tabBar: {
            activeTintColor: theme === 'dark' ? 'white' : 'black', 
            inactiveTintColor: theme === 'dark' ? 'grey' : 'darkgrey', 
            backgroundColor: 'rgba(1, 193, 219, 1)', 
            //backgroundColor: theme === 'dark' ? 'black' : 'white', 
            borderColor: theme === 'dark' ? 'black' : 'white', 
            position: 'absolute', 
            bottom: '2.5%', 
            left: '5%', 
            right: '5%',
            borderRadius: '30%', 
            height: '7%', 
            paddingVertical: '2%', 
            paddingBottom: '2.5%',
            borderTopWidth: '0%', 
            shadowColor: theme === 'dark' ? '#3A3A3A' : '#000',
            shadowOffset: { width: '0%', height: '1%' },
            shadowOpacity: theme === 'dark' ? '0.8%' : '0.4%',
            shadowRadius: '20%',
        },
        tabBarLabel: {
            fontSize: 11,
        },
        input: {
            height: 44,
            width: '100%', 
            backgroundColor: themeStyles[theme].inputBackground,
            borderColor: themeStyles[theme].borderColor,
            borderWidth: 1,
            borderRadius: 10,
            marginBottom: '5.5%',
            paddingLeft: '4%',
            color: themeStyles[theme].textColor, 
        },
        inputPreLogin: {
            height: 50,
            width: '71%', 
            backgroundColor: themeStyles[theme].inputBackground,
            borderColor: themeStyles[theme].borderColor,
            borderWidth: 1,
            borderRadius: 10,
            marginBottom: '4.5%',
            paddingLeft: '4%',
            color: themeStyles[theme].textColor, 
        },
        button: {
            height: 44,
            width: '100%',
            backgroundColor: themeStyles[theme].backgroundColor,
            marginBottom: '5.7%',
            borderRadius: 10,
            justifyContent: 'center',
            alignItems: 'center',
        },
        buttonPreLogin: {
            height: 50,
            width: 250,
            backgroundColor: themeStyles[theme].backgroundColor,
            marginBottom: '3%',
            borderRadius: 10,
            justifyContent: 'center',
            alignItems: 'center',
            marginTop: '0.5%',
        },
        buttonText: {
            color: themeStyles[theme].textColor,
            fontSize: 16,
            fontWeight: 'bold',
        },
        buttonTextPreLogin: {
            color: themeStyles[theme].textColor,
            fontSize: 16,
            fontWeight: 'bold',
        },
        title: {
            fontSize: 22,
            fontWeight: 'bold',
            marginBottom: '6%',
            color: themeStyles[theme].textColor, 
            textAlign: 'center', 
        },
        settingItem: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            width: '100%',
            marginBottom: '3%',
        },
        settingText: {
            fontSize: 18,
            color: themeStyles[theme].textColor, 
        },
        fileInput: {
            height: 44,
            width: '100%', 
            backgroundColor: themeStyles[theme].inputBackground,
            marginBottom: 16,
            borderRadius: 10,
            justifyContent: 'center',
            alignItems: 'center',
            borderWidth: 1,
            borderColor: themeStyles[theme].borderColor,
        },
        fileInputText: {
            color: themeStyles[theme].textColor,
            fontSize: 16,
        },
        card: {
            width: '96%', 
            backgroundColor: themeStyles[theme].cardBackground,
            borderRadius: '10%',
            padding: '6%',
            marginBottom: '6%',
            shadowColor: theme === 'dark' ? '#3A3A3A' : '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: theme === 'dark' ? '0.8%' : '0.4%',
            shadowRadius: '4%',
            elevation: '1%',
            margin: '1%',
            marginTop: '2%',
            marginLeft: '2%',
            marginLeft: '2%'
        },
        cardHeader: {
            fontSize: 18,
            color: themeStyles[theme].textColor,
            fontWeight: 'bold',
            marginBottom: 10,
        },
        scrollView: {
            backgroundColor: themeStyles[theme].containerBackground, 
            marginBottom: 90,
        },
        header: {
            fontSize: 28,
            fontWeight: 'bold',
            color: themeStyles[theme].textColor, 
            marginBottom: 20,
        },
        footer: {
            marginTop: 20,
            marginBottom: 10,
        },
        footerText: {
            fontSize: 14,
            color: themeStyles[theme].textColor,
        },
        dropZone: {
            width: '100%',
            height: 150,
            borderRadius: 10,
            borderWidth: 2,
            borderColor: themeStyles[theme].backgroundColor,
            borderStyle: 'dashed',
            justifyContent: 'center',
            alignItems: 'center',
            marginBottom: '5%',
        },
        dropZoneText: {
            textAlign: 'center',
            color: '#007bff',
            fontSize: 16,
        },
        sendButton: {
            backgroundColor: themeStyles[theme].backgroundColor,
            borderRadius: 10,
            justifyContent: 'center',
            alignItems: 'center',
            paddingHorizontal: '5%',
            paddingVertical: 10, 
            height: 50,
        },
        fileInfo: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            marginTop: 10,
        },
        dropZoneText: {
            fontSize: 16,
            fontWeight: 'bold',
        },
        contractText: {
            fontSize: 16,
            color: theme === 'dark' ? 'white' : 'black',
        },
        contractHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
        },
        expandedSection: {
            paddingTop: 10,
        },
        contractItemAnimation: {
            marginBottom: 10,
            paddingHorizontal: 10,
            paddingTop: 10,
            backgroundColor: themeStyles[theme].backgroundColor,
            borderRadius: 10,
            borderColor: '#ddd',
        },
        contractHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
        },
        expandedSection: {
            marginTop: 10,
        },
        smartContractButton: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            padding: 10,
            marginTop: 10,
            borderRadius: 10,
            backgroundColor: theme === 'dark' ? '#2D2D2D' : '#EFEFEF',
        },
        noContractsText: {
            textAlign: 'center',
            color: themeStyles[theme].textColor,
            marginTop: 20, 
            fontSize: 16,
        },
        EditorContainer: {
            flex: 1,
        },
        editor: {
            flex: 1,
            borderColor: themeStyles[theme].backgroundColor,
            backgroundColor: themeStyles[theme].inputBackground,
            color: themeStyles[theme].textColor,
            padding: 10,
            textAlignVertical: 'top',
            marginBottom: 90,
        },
        errorIcon: {
            color: 'red', 
        },
        errorText: {
            marginLeft: 5, 
            color: 'red', 
            fontSize: 14, 
        },
        errorIconContainerSignUp: {
            position: 'absolute',
            right: 20,
            top: 70,
        },
        errorIconContainer: {
            position: 'absolute',
            right: 5,
            top: 5,
        },
        centeredView: {
            flex: 1,
            justifyContent: "center",
            alignItems: "center",
        },
        modalView: {
            width: '80%', 
            margin: 20,
            backgroundColor: themeStyles[theme].inputBackground,
            borderRadius: 20,
            padding: 25,
            alignItems: "flex-start", 
            shadowColor: "#000",
            shadowOffset: {
                width: 0,
                height: 2
            },
            shadowOpacity: 0.25,
            shadowRadius: 4,
            elevation: 5
        },
        modalText: {
            color: themeStyles[theme].textColor,
            marginBottom: 15,
            textAlign: "center"
        },
        errorListItem: {
            color: 'red',
            alignSelf: 'stretch',
            textAlign: 'left',
            marginBottom: '5%',
        },
        textStyle: {
            color: themeStyles[theme].textColor,
            fontWeight: "bold",
            textAlign: "center"
        },
        exitButton: {
            position: 'absolute',
            top: 5,
            right: 5,
            justifyContent: 'center',
            alignItems: 'center',
            shadowColor: theme === 'dark' ? '#3A3A3A' : '#000',
            shadowOffset: {
                width: 0,
                height: 2
            },
            shadowOpacity: 0.15,
            shadowRadius: 3.84, 
            elevation: 5,
        },
        exitButtonText: {
            color: 'white',
            fontWeight: 'bold',
        },
        centeredContainer: {
            flex: 1, 
            justifyContent: 'center',
            alignItems: 'center',
            marginTop: '2%', 
        },
        baseContainer: {
            flex: 1, 
            backgroundColor: theme === 'dark' ? '#1A1A1A' : 'white', 
        },
        separatorLine: {
            position: 'absolute',
            height: 0.3, 
            backgroundColor: theme === 'dark' ? 'grey' : 'darkgrey',
            bottom: 90,
            left: 0,
            right: 0,
        },
        activityIndicator: {
            paddingTop: '10%',
        },
        generalText: {
            color: theme === 'dark' ? 'white' : 'black', 
        },
        contractItemText: {
            color: theme === 'dark' ? 'white' : 'black', 
            marginLeft: 5,
        },
        postsContainer: {
            flexDirection: 'row',
            marginTop: 10,
            alignItems: 'center', 
            justifyContent: 'space-between', 
        },
        postsButtonText: {
            flexDirection: 'row', 
            alignItems: 'center', 
            marginRight: 0,
        },
        postsViewContainer: {
            flexDirection: 'row', 
            marginBottom: '10%',
        },
        inputForumScreen: {
            flex: 1, 
            height: 44,
            backgroundColor: themeStyles[theme].inputBackground,
            borderColor: themeStyles[theme].borderColor,
            color: themeStyles[theme].textColor, 
            borderWidth: 1,
            borderRadius: 10,
            paddingLeft: '4%',
            marginRight: 10,
        },
        buttonForumScreen: {
            height: 44,
            backgroundColor: themeStyles[theme].backgroundColor,
            borderRadius: 10,
            justifyContent: 'center',
            alignItems: 'center', 
            paddingHorizontal: 20,
        },
        flatListPostsContainer: {
            flex: 1,
            marginBottom: 90, 
            paddingTop: 25,
        },
        flatListCommentsContainer: {
            width: '100%',
            marginBottom: 90,
        },
        inputCommentsScreen: {
            height: 44,
            width: '96%', 
            backgroundColor: themeStyles[theme].inputBackground,
            borderColor: themeStyles[theme].borderColor,
            borderWidth: 1,
            borderRadius: 10,
            marginBottom: '5.5%',
            paddingLeft: '4%',
            color: themeStyles[theme].textColor, 
        },
        buttonCommentsScreen: {
            height: 44,
            width: '96%',
            backgroundColor: themeStyles[theme].backgroundColor,
            marginBottom: '5.7%',
            borderRadius: 10,
            justifyContent: 'center',
            alignItems: 'center',
        },
        listFooterContainer: {
            width: 300, 
            paddingBottom: 30,
        },
        regularPadding: {
            paddingTop: 20,
            paddingBottom: 5,
        },
    });
};

export default getStyles;
