version: '3'

services:
  web:
    build:
      context: ./ASACBackEnd
    command: daphne ASACBackEnd.asgi:application --bind 0.0.0.0 --port 8000
    volumes:
      - ./ASACBackEnd:/ASACImage
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
