version: '3'

services:
  web:
    build:
      context: ./backend
    command: daphne AIChainContracts.asgi:application --bind 0.0.0.0 --port 8000
    volumes:
      - ./backend:/backend
      - static_volume:/backend/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_NAME=aiccdb
      - DB_USER=admin
      - DB_PASS=admin123!!!
      - DB_PORT=5432
      - DEBUG=False

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - static_volume:/backend/staticfiles

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email ezzat.alsalibi@kcl.ac.uk --agree-tos --no-eff-email --force-renewal -d alsalibiaicontracts.co.uk -d www.alsalibiaicontracts.co.uk

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=aiccdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123!!!
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
      args:
        TOKEN: ${TOKEN} 
    volumes:
      - ./frontend:/frontend
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
