# Generated by Django 5.0.4 on 2024-07-28 18:51

import Contracts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=255, validators=[Contracts.validators.validate_contract_name])),
                ('employer_address', models.CharField(max_length=42, validators=[Contracts.validators.validate_ethereum_address, Contracts.validators.validate_hexadecimal])),
                ('auth_app_address', models.CharField(max_length=42, validators=[Contracts.validators.validate_ethereum_address, Contracts.validators.validate_hexadecimal])),
                ('token_contract_interface', models.TextField(max_length=42, validators=[Contracts.validators.validate_ethereum_address, Contracts.validators.validate_hexadecimal])),
                ('contract_content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'contract_name')},
            },
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('contract_name', models.CharField(max_length=255, validators=[Contracts.validators.validate_contract_name])),
                ('employer_address', models.CharField(max_length=42, validators=[Contracts.validators.validate_ethereum_address, Contracts.validators.validate_hexadecimal])),
                ('auth_app_address', models.CharField(max_length=42, validators=[Contracts.validators.validate_ethereum_address, Contracts.validators.validate_hexadecimal])),
                ('token_contract_interface', models.TextField(validators=[Contracts.validators.validate_ethereum_address, Contracts.validators.validate_hexadecimal])),
                ('legal_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_contracts', to='Contracts.employmentcontract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'contract_name')},
            },
        ),
    ]
