# Generated by Django 5.0.3 on 2024-03-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PushToken',
            new_name='AuthenticationPushToken',
        ),
    ]
