# Generated by Django 4.2.6 on 2024-01-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_pushtoken_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
