# Generated by Django 4.2.6 on 2024-01-24 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authorisation_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
