# Generated by Django 5.0.4 on 2024-05-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_rename_pushtoken_notificationpushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpushtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
