name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11.2
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.2'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        cd backend
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        cd backend
        pytest

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.14.0'

    - name: Install npm dependencies
      run: |
        cd frontend
        npm install --legacy-peer-deps

    - name: Run React Native tests
      run: |
        cd frontend
        npm run test
