# Generated by Django 4.2.6 on 2024-03-06 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=255)),
                ('employer_address', models.CharField(max_length=42)),
                ('auth_app_address', models.CharField(max_length=42)),
                ('token_contract_interface', models.TextField()),
                ('contract_content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('employer_usdc_address', models.CharField(max_length=42)),
                ('employee_usdc_address', models.CharField(max_length=42)),
                ('authorized_app_usdc_address', models.CharField(max_length=42)),
                ('monthly_salary', models.DecimalField(decimal_places=5, max_digits=20)),
                ('usdc_token_contract_interface', models.TextField()),
                ('start_date', models.BigIntegerField()),
                ('termination_date', models.BigIntegerField()),
                ('performance_score', models.IntegerField()),
                ('performance_threshold', models.IntegerField()),
                ('is_employed', models.BooleanField(default=True)),
                ('salary_type', models.CharField(choices=[('monthly', 'Monthly'), ('bi-weekly', 'Bi-Weekly'), ('weekly', 'Weekly')], max_length=10)),
                ('legal_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_contracts', to='Contracts.employmentcontract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
