# Generated by Django 4.2.6 on 2024-03-06 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=255)),
                ('employer_address', models.CharField(max_length=42)),
                ('auth_app_address', models.CharField(max_length=42)),
                ('token_contract_interface', models.TextField()),
                ('contract_content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('contract_name', models.CharField(max_length=255)),
                ('employer_address', models.CharField(max_length=42)),
                ('auth_app_address', models.CharField(max_length=42)),
                ('token_contract_interface', models.TextField()),
                ('legal_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_contracts', to='Contracts.employmentcontract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
