# Generated by Django 5.0.3 on 2024-03-18 23:35

import Contracts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentcontract',
            name='auth_app_address',
            field=models.CharField(max_length=42, validators=[Contracts.validators.validate_ethereum_address, Contracts.validators.validate_hexadecimal]),
        ),
        migrations.AlterField(
            model_name='employmentcontract',
            name='contract_name',
            field=models.CharField(max_length=255, validators=[Contracts.validators.validate_contract_name]),
        ),
        migrations.AlterField(
            model_name='employmentcontract',
            name='employer_address',
            field=models.CharField(max_length=42, validators=[Contracts.validators.validate_ethereum_address, Contracts.validators.validate_hexadecimal]),
        ),
        migrations.AlterField(
            model_name='employmentcontract',
            name='token_contract_interface',
            field=models.TextField(max_length=42, validators=[Contracts.validators.validate_ethereum_address, Contracts.validators.validate_hexadecimal]),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='auth_app_address',
            field=models.CharField(max_length=42, validators=[Contracts.validators.validate_ethereum_address, Contracts.validators.validate_hexadecimal]),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='contract_name',
            field=models.CharField(max_length=255, validators=[Contracts.validators.validate_contract_name]),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='employer_address',
            field=models.CharField(max_length=42, validators=[Contracts.validators.validate_ethereum_address, Contracts.validators.validate_hexadecimal]),
        ),
        migrations.AlterField(
            model_name='smartcontract',
            name='token_contract_interface',
            field=models.TextField(validators=[Contracts.validators.validate_ethereum_address, Contracts.validators.validate_hexadecimal]),
        ),
    ]
