# Generated by Django 5.0.3 on 2024-03-20 16:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contracts', '0002_alter_employmentcontract_auth_app_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employmentcontract',
            unique_together={('user', 'contract_name')},
        ),
        migrations.AlterUniqueTogether(
            name='smartcontract',
            unique_together={('user', 'contract_name')},
        ),
    ]
